import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "animate.css";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <div className="flex flex-col items-center">
          <Header />
          <span className="border-[1px] border-b-[##e3e3e3] w-full" />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
